config/routes.rb
Rails.application.routes.draw do
  

  root 'static_pages#home'
  
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get     'upload'=>  'upload#new'
  post    'uploadsubmit'=> 'upload#create'
  resources :users
  resources :upload

end

app/models/csv_upload_file.rb
class CsvUploadFile < ActiveRecord::Base
	 mount_uploader :attachment, AttachmentUploader
	 validates :name, presence: true,length: {maximum: 12 }

	
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :name, presence: true, length: {maximum: 50 }
	validates :email, presence: true, length: {maximum: 100 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } 
	has_secure_password
	validates :password, presence: true, length: {minimum: 4 }, allow_nil: true
	def User.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create 
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    	log_in user
      	redirect_to user
                
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end
  def destroy
  	log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  def about
  end
  def contact
  end
  
  
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  before_action :logged_in_user, only: [:create]
  before_action :correct_user,   only: [:create]
  def new
  	
  end
  def create
      @upload = CsvUploadFile.new(upload_params)
      
      if @upload.save
        
         redirect_to upload_path, notice: "The file #{@upload.name} has been uploaded."
      else
        flash[:danger]="Upload failed"
         #redirect_to upload_path
         render 'new'
      end
      
   end
   def logged_in_user
    unless logged_in?
      store_location
      flash[:danger]="Please Log in to access the page !!!!"
      redirect_to login_url
    end
  end
   def correct_user
      @user = User.find(params[:id])
      flash[:danger]="You cant upload files from others profile"
      redirect_to(current_user) unless current_user?(@user)
    end

   private
      def upload_params
      	params.require(:upload).permit(:name, :attachment)
   	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :logged_in_user, only: [:index,:edit, :update , :destroy]
   before_action :correct_user,   only: [:edit, :update]
   before_action :admin_user,     only: [:destroy]
  def new
  	@user=User.new
  end
  def show
  	@user=User.find(params[:id])
  end
  def create
  	@user=User.new(user_params)
  	if @user.save
  		log_in @user
  		flash.now[:success] = "Welcome to the My App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end
  def edit
    @user = User.find(params[:id])
  end
   def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash.now[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger]="Please Log in to access the page !!!!"
      redirect_to login_url
    end
  end
   def correct_user
      @user = User.find(params[:id])
      flash[:danger]="You cant edit others profile!"
      redirect_to(current_user) unless current_user?(@user)
    end
    def index
        @users = User.paginate(page: params[:page])
    end

  private
  	def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
	    base_title = "Ruby on Rails"
	    if page_title.empty?
	      base_title
	    else
	      page_title + " | " + base_title
	    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    	session[:user_id] = user.id
  	end
  	def current_user
    	@current_user ||= User.find_by(id: session[:user_id])
 	end
 	def logged_in?
    	!current_user.nil?
 	end
 	def log_out
	    session.delete(:user_id)
	    @current_user = nil
  	end
  	def current_user?(user)
    	user == current_user
  	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar//#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created 
    by <a href="https://www.facebook.com/biharimunda">Rishabh</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "ShopperQuick WebCrawler", root_path , id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "About",   about_path %></li>
            
            <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
            
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

      <%= render 'layouts/footer' %>
       
    </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<% provide(:title, "About") %>

app/views/static_pages/contact.html.erb
<h1> Contact</h1>
<% provide(:title,"Contact") %>
<h2>Work Under Progress</h2>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<% provide(:title,"Help") %>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>

<div class="center jumbotron">
  <h1>ShopperQuick WebCrawler</h1>

  <h2>
    Meet ShopperQuick on the Web
    <a href="https://shopperquick.com/">ShopperQuick Homepage</a>
    
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("logo.png", alt: "ShopperQuick logo"),
            'https://shopperquick.com/skin/frontend/sm_lovefashion/default/images/logo.png' %>

app/views/upload/new.html.erb
<% provide(:title,"File Upload") %>
<div class="row">
<div class = "col-md-6 col-md-offset-3 ">
   <%= form_for :upload, url: uploadsubmit_path do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>
</div>

app/views/users/_user.html.erb
<li>
 
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    
     </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title,"Sign Up") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user,:validate => true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>


      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <%= link_to '<button type="button">New File Upload</button>'.html_safe, upload_path %>

</div>